version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
    networks:
      - laravel
    depends_on:
      - db
    ports:
      - "9000:9000"  # PHP-FPM port

  webserver:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"  # Nginx exposed port 8000
    volumes:
      - .:/var/www
      - ./storage/:/etc/nginx/conf.d/
    networks:
      - laravel
    depends_on:
      - app

  db:
    image: mysql:8.0
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: mutia
      MYSQL_DATABASE: PetshopFramework
      MYSQL_PASSWORD: mutia
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - laravel
    ports:
      - "3334:80"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: db  # MySQL service name
      PMA_PORT: 3306  # Default MySQL port
      MYSQL_ROOT_PASSWORD: mutia # Root password for MySQL
    ports:
      - "8082:80"  # Set a different port for phpMyAdmin
    networks:
      - laravel
    depends_on:
      - db

networks:
  laravel:

volumes:
  dbdata:
